"""empty message

Revision ID: 6e5672b8b7be
Revises: 40ab127d9e01
Create Date: 2017-11-15 23:27:26.436316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5672b8b7be'
down_revision = '40ab127d9e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('focuses', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'likes')
    op.drop_column('questions', 'focuses')
    op.drop_column('answers', 'likes')
    # ### end Alembic commands ###
